name: SpaciousLib
version: 1.7.7
main: org.anhcraft.spaciouslib.SpaciousLib
softdepend: [Vault,PlayerPoints]
authors: [anhcraft]
description: A useful library for your Spigot/Bungeecord plugins and Java programs
website: https://anhcraft.org/
api-version: 1.13